#!/usr/bin/env python3
"""Turn the authored master walking order into the route lookup.

This is an authoring aid, not a route finder. It does not decide anything. It
takes the one sequence a human worked out on a map and, for each of the ten
combinations, removes the stops belonging to the two topics that combination did
not choose. The relative order of everything left is untouched.

That is why it is safe. A greedy nearest-neighbour ordering produced walks of 7
to 10 km with legs up to 3.3 km, because shortest-next is not the same as
sensible-next. Subsetting an order somebody walked in their head keeps the
judgement and just drops the stops that are not wanted.

Any combination that needs different treatment can be given an explicit order in
the overrides block of master_order.json, and this script will leave it alone.

    python3 pipeline/author_routes.py [--check]

--check reports what would change without writing anything.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from combos import all_combos                      # noqa: E402
import geo                                         # noqa: E402

BASE = Path(__file__).resolve().parent.parent
CONTENT = BASE / "content"
TARGET_STOPS = 18
STOPS_PER_TOPIC = 6


def load(name):
    return json.loads((CONTENT / name).read_text(encoding="utf-8"))


def main():
    check_only = "--check" in sys.argv
    topics = [t["id"] for t in load("topics.json")["topics"]]
    # A stop carrying _unused is bench content: written, kept, not in the walk.
    stops = {s["id"]: s for s in load("stops.json")["stops"] if not s.get("_unused")}
    master_doc = load("master_order.json")
    master = master_doc["order"]
    overrides = master_doc.get("overrides", {})

    missing = [s for s in master if s not in stops]
    if missing:
        print(f"master order names stops that do not exist: {missing}")
        return 1
    unplaced = [s for s in stops if s not in master]
    if unplaced:
        print(f"stops missing from the master order: {unplaced}")
        return 1
    if len(master) != len(set(master)):
        print("the master order lists a stop twice")
        return 1

    routes, failures = {}, 0
    for key, chosen in all_combos(topics, 3):
        wanted = set(chosen)
        ids = overrides.get(key) or [s for s in master if stops[s]["topic"] in wanted]
        draft = len(ids) != TARGET_STOPS

        points = [(i, stops[i]["lat"], stops[i]["lon"]) for i in ids]
        result = geo.check(points)
        counts = {t: sum(1 for i in ids if stops[i]["topic"] == t) for t in sorted(wanted)}
        gated = sum(1 for i in ids if stops[i].get("gate"))

        routes[key] = {"draft": draft, "stops": ids}
        if key in overrides:
            routes[key]["note"] = "Order set by hand in master_order.json rather " \
                                  "than inherited from the master sequence."

        flag = "ok    "
        if result["problems"]:
            flag = "FAIL  "
            failures += 1
        elif result["notes"]:
            flag = "look  "
        print(f"  {flag} {key:<20} {len(ids)} stops "
              f"{'/'.join(str(counts[t]) for t in sorted(wanted))}  "
              f"{result['total_walk_m'] / 1000:.1f} km  "
              f"{result['total_minutes']:.0f} min walking  "
              f"{gated} gated  {result['reversals']} back")
        for p in result["problems"]:
            print(f"         ! {p}")
        for n in result["notes"]:
            print(f"         - {n}")
        for t, n in counts.items():
            if n != STOPS_PER_TOPIC:
                print(f"         ! topic {t} contributes {n} stops, expected {STOPS_PER_TOPIC}")

    if check_only:
        print("\n--check: nothing written")
        return 1 if failures else 0

    out = CONTENT / "routes.json"
    doc = {
        "_comment": "THE ROUTE LOOKUP IS AUTHORITATIVE. It fixes which stops a "
                    "combination gets and the order they are walked in. Nothing "
                    "scores, ranks or reorders these. GENERATED by "
                    "pipeline/author_routes.py from content/master_order.json; "
                    "to change a route, change the master order or add an "
                    "override there, then regenerate.",
        "target_stops": TARGET_STOPS,
        "stops_per_topic": STOPS_PER_TOPIC,
        "routes": routes,
    }
    out.write_text(json.dumps(doc, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"\n{out} written: {len(routes)} routes, {failures} with problems")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
