#!/usr/bin/env python3
"""Emit the content as Postgres schema and seed data.

The POC serves static artefacts and needs no database at all. This exists
because of a decision recorded in docs/decisions.md: ship static, but keep the
builder emitting SQL, so a backend can be added later without rewriting the
content pipeline. It runs on every build so that it cannot quietly rot.

The schema is deliberately, aggressively simpler than the one this project was
copied from. That one hid answers from the client behind deny-all row level
security and security-definer functions, because a treasure hunt with a visible
answer is not a treasure hunt. There are no answers here. Every word of this
content is meant to be read by the person holding the phone, so the tables are
plain, the grants are read-only to anyone, and there is nothing to withhold.

    python3 pipeline/emit_seed_sql.py [--out sql/seed.sql]
"""
import json
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
CONTENT = BASE / "content"


def q(value):
    """Quote a value for SQL. None becomes NULL."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


SCHEMA = """\
-- Generated by pipeline/emit_seed_sql.py. Do not edit by hand.
-- Regenerate with: python3 pipeline/emit_seed_sql.py

begin;

drop table if exists route_stops cascade;
drop table if exists routes cascade;
drop table if exists stops cascade;
drop table if exists topics cascade;

create table topics (
  id            text primary key,
  name          text not null,
  blurb         text not null,
  blurb_spoken  text,
  sort          int  not null
);

create table stops (
  id             text primary key,
  topic_id       text not null references topics(id),
  title          text not null,
  where_text     text not null,
  lat            double precision not null,
  lon            double precision not null,
  -- a null radius means the stop is not location-gated, which is most of them
  gate_radius_m  int,
  gate_prompt    text,
  -- the soft "have you found it yet" prompt, also optional and also most-of-them-not
  nudge_prompt   text,
  nudge_confirm  text,
  look           text not null,
  look_spoken    text,
  after_text     text not null,
  after_spoken   text,
  -- reserved: audio is designed for but not built
  audio_url      text,
  constraint gate_is_complete check ((gate_radius_m is null) = (gate_prompt is null)),
  constraint nudge_is_complete check ((nudge_prompt is null) = (nudge_confirm is null))
);

create table routes (
  combo_key  text primary key,
  draft      boolean not null default true,
  note       text
);

-- The route lookup is authoritative: this table fixes which stops a
-- combination gets AND the order they are walked in. Nothing ranks or reorders.
create table route_stops (
  combo_key  text not null references routes(combo_key) on delete cascade,
  position   int  not null,
  stop_id    text not null references stops(id),
  primary key (combo_key, position),
  unique (combo_key, stop_id)
);

create index stops_topic_idx on stops(topic_id);

-- Content ships to the client by design. There is nothing here to hide, so the
-- policy is read-only for everyone and writes go through the pipeline.
alter table topics      enable row level security;
alter table stops       enable row level security;
alter table routes      enable row level security;
alter table route_stops enable row level security;

create policy read_topics      on topics      for select using (true);
create policy read_stops       on stops       for select using (true);
create policy read_routes      on routes      for select using (true);
create policy read_route_stops on route_stops for select using (true);
"""


def main():
    args = sys.argv[1:]
    out = Path(args[args.index("--out") + 1]) if "--out" in args else BASE / "sql" / "seed.sql"
    topics = json.loads((CONTENT / "topics.json").read_text(encoding="utf-8"))["topics"]
    stops = json.loads((CONTENT / "stops.json").read_text(encoding="utf-8"))["stops"]
    routes_doc = json.loads((CONTENT / "routes.json").read_text(encoding="utf-8"))

    lines = [SCHEMA, "\n-- topics\n"]
    for i, t in enumerate(topics):
        lines.append(
            f"insert into topics (id, name, blurb, blurb_spoken, sort) values "
            f"({q(t['id'])}, {q(t['name'])}, {q(t['blurb'])}, "
            f"{q(t.get('blurb_spoken'))}, {i});\n")

    lines.append("\n-- stops\n")
    for s in stops:
        gate = s.get("gate") or {}
        nudge = s.get("nudge") or {}
        lines.append(
            "insert into stops (id, topic_id, title, where_text, lat, lon, "
            "gate_radius_m, gate_prompt, nudge_prompt, nudge_confirm, "
            "look, look_spoken, after_text, after_spoken) values (\n"
            f"  {q(s['id'])}, {q(s['topic'])}, {q(s['title'])}, {q(s['where'])},\n"
            f"  {q(s['lat'])}, {q(s['lon'])},\n"
            f"  {q(gate.get('radius_m'))}, {q(gate.get('prompt'))},\n"
            f"  {q(nudge.get('prompt'))}, {q(nudge.get('confirm'))},\n"
            f"  {q(s['look'])}, {q(s.get('look_spoken'))},\n"
            f"  {q(s['after'])}, {q(s.get('after_spoken'))});\n")

    lines.append("\n-- routes, and the authoritative stop order\n")
    for key, route in routes_doc["routes"].items():
        lines.append(
            f"insert into routes (combo_key, draft, note) values "
            f"({q(key)}, {q(bool(route.get('draft')))}, {q(route.get('note'))});\n")
        for pos, sid in enumerate(route.get("stops", []), start=1):
            lines.append(
                f"insert into route_stops (combo_key, position, stop_id) values "
                f"({q(key)}, {pos}, {q(sid)});\n")

    lines.append("\ncommit;\n")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(lines), encoding="utf-8")
    print(f"{out} written: {len(topics)} topics, {len(stops)} stops, "
          f"{len(routes_doc['routes'])} routes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
