-- Generated by pipeline/emit_seed_sql.py. Do not edit by hand.
-- Regenerate with: python3 pipeline/emit_seed_sql.py

begin;

drop table if exists route_stops cascade;
drop table if exists routes cascade;
drop table if exists stops cascade;
drop table if exists topics cascade;

create table topics (
  id            text primary key,
  name          text not null,
  blurb         text not null,
  blurb_spoken  text,
  sort          int  not null
);

create table stops (
  id             text primary key,
  topic_id       text not null references topics(id),
  title          text not null,
  where_text     text not null,
  lat            double precision not null,
  lon            double precision not null,
  -- a null radius means the stop is not location-gated, which is most of them
  gate_radius_m  int,
  gate_prompt    text,
  -- the soft "have you found it yet" prompt, also optional and also most-of-them-not
  nudge_prompt   text,
  nudge_confirm  text,
  look           text not null,
  look_spoken    text,
  after_text     text not null,
  after_spoken   text,
  -- reserved: audio is designed for but not built
  audio_url      text,
  constraint gate_is_complete check ((gate_radius_m is null) = (gate_prompt is null)),
  constraint nudge_is_complete check ((nudge_prompt is null) = (nudge_confirm is null))
);

create table routes (
  combo_key  text primary key,
  draft      boolean not null default true,
  note       text
);

-- The route lookup is authoritative: this table fixes which stops a
-- combination gets AND the order they are walked in. Nothing ranks or reorders.
create table route_stops (
  combo_key  text not null references routes(combo_key) on delete cascade,
  position   int  not null,
  stop_id    text not null references stops(id),
  primary key (combo_key, position),
  unique (combo_key, stop_id)
);

create index stops_topic_idx on stops(topic_id);

-- Content ships to the client by design. There is nothing here to hide, so the
-- policy is read-only for everyone and writes go through the pipeline.
alter table topics      enable row level security;
alter table stops       enable row level security;
alter table routes      enable row level security;
alter table route_stops enable row level security;

create policy read_topics      on topics      for select using (true);
create policy read_stops       on stops       for select using (true);
create policy read_routes      on routes      for select using (true);
create policy read_route_stops on route_stops for select using (true);

-- topics
insert into topics (id, name, blurb, blurb_spoken, sort) values ('roman', 'Roman London', 'Londinium is still here. Most of it is below you, some of it is at eye level.', null, 0);
insert into topics (id, name, blurb, blurb_spoken, sort) values ('fire', 'The Great Fire', 'Four days in 1666, and the fifty years of building that followed.', 'Four days in sixteen sixty-six, and the fifty years of building that followed.', 1);
insert into topics (id, name, blurb, blurb_spoken, sort) values ('rivers', 'Lost Rivers', 'The water is still running. It is just under the road.', null, 2);
insert into topics (id, name, blurb, blurb_spoken, sort) values ('marks', 'Small Marks', 'Boundary stones, ghost signs and iron. Nothing here is famous.', null, 3);
insert into topics (id, name, blurb, blurb_spoken, sort) values ('fleet', 'Fleet Street', 'Five hundred years of printing on one street, and none of it left.', null, 4);

-- stops
insert into stops (id, topic_id, title, where_text, lat, lon, gate_radius_m, gate_prompt, nudge_prompt, nudge_confirm, look, look_spoken, after_text, after_spoken) values (
  'st-brides-spire', 'fire', 'St Bride''s, Fleet Street', 'Fleet Street, at the top of Bride Lane',
  51.5139, -0.1053,
  null, null,
  null, null,
  'Step back until you can see the whole spire.

Count the tiers. Each one is smaller than the one below it. Four of them, and then a point.

Now think of a wedding cake.', null,
  'The story goes that a baker on Ludgate Hill called William Rich could see this spire from his shop, and built a cake in its shape for his own wedding.

Nobody has ever proved it. But the shape is the shape, and every tiered wedding cake since is a copy of a church steeple you have walked past a hundred times without looking up.

Wren gave every one of his churches a different spire, and he did it on purpose. From street level you hardly saw the building at all. What you saw was the spire, over the rooftops, from three streets away. So that is where he put the work.

This one is the tallest he ever built.', null);
insert into stops (id, topic_id, title, where_text, lat, lon, gate_radius_m, gate_prompt, nudge_prompt, nudge_confirm, look, look_spoken, after_text, after_spoken) values (
  'st-dunstan-west-clock', 'fleet', 'The clock at St Dunstan-in-the-West', '186a Fleet Street, on the north side',
  51.5142, -0.1092,
  null, null,
  'There is a clock sticking out over the pavement, and two men standing next to it. Have you found them?', 'Found them',
  'Look up at the clock hanging out over the street.

Two figures stand either side of a bell. They are holding clubs.

Wait for the quarter hour if you have time. They turn, and they strike it.', null,
  'That clock was made in 1671, and it was the first public clock in London with a minute hand.

Think about what that means. Before this, London told the time to the nearest quarter of an hour and considered that plenty.

The two giants are Gog and Magog, the old guardians of the city. They struck the hours here for two hundred years. Then in 1830 the church was rebuilt, the clock was sold to a marquess and carted off to a villa in Regent''s Park. It only came back in 1935.

One more thing before you walk on. Look at the porch, to your left. The statue of Elizabeth the First standing there was carved in 1586, while she was alive and on the throne. It stood on Ludgate until the gate came down.

It is the oldest outdoor statue of an English monarch in London, and it is on a wall on Fleet Street, and almost nobody stops.', 'That clock was made in sixteen seventy-one, and it was the first public clock in London with a minute hand.

Think about what that means. Before this, London told the time to the nearest quarter of an hour and considered that plenty.

The two giants are Gog and Magog, the old guardians of the city. They struck the hours here for two hundred years. Then in eighteen thirty the church was rebuilt, the clock was sold to a marquess and carted off to a villa in Regent''s Park. It only came back in nineteen thirty-five.

One more thing before you walk on. Look at the porch, to your left. The statue of Elizabeth the First standing there was carved in fifteen eighty-six, while she was alive and on the throne. It stood on Ludgate until the gate came down.

It is the oldest outdoor statue of an English monarch in London, and it is on a wall on Fleet Street, and almost nobody stops.');
insert into stops (id, topic_id, title, where_text, lat, lon, gate_radius_m, gate_prompt, nudge_prompt, nudge_confirm, look, look_spoken, after_text, after_spoken) values (
  'holborn-viaduct-fleet', 'rivers', 'Holborn Viaduct', 'On the bridge, above Farringdon Street',
  51.5176, -0.1046,
  70, 'This one only opens when you are standing on the bridge itself.',
  null, null,
  'You are standing on a bridge.

Go to the parapet and look over. That is Farringdon Street below you, a long way down.

Now lift your eyes and follow the low ground. It runs away north, and south towards Ludgate. You are looking along a valley in the middle of London.', null,
  'That valley is a river. The Fleet is still running down it, in a pipe, under the road you are looking at.

It was London''s second river. Boats came up it as far as Holborn. By the 1700s it was an open sewer and people were dumping dead dogs in it, so the city covered it over, a stretch at a time. Farringdon Street is the lid.

The bridge is here because of the river too. The valley was so steep that carts had to be unloaded at the bottom and hauled up empty. It took six years and more than two million pounds to solve a problem the water had made.

Once you know the Fleet is there, you cannot stop seeing it. The dip at Ludgate Circus. The way Fleet Street runs downhill to it. Every road here bends around a river nobody can see.', 'That valley is a river. The Fleet is still running down it, in a pipe, under the road you are looking at.

It was London''s second river. Boats came up it as far as Holborn. By the seventeen hundreds it was an open sewer and people were dumping dead dogs in it, so the city covered it over, a stretch at a time. Farringdon Street is the lid.

The bridge is here because of the river too. The valley was so steep that carts had to be unloaded at the bottom and hauled up empty. It took six years and more than two million pounds to solve a problem the water had made.

Once you know the Fleet is there, you cannot stop seeing it. The dip at Ludgate Circus. The way Fleet Street runs downhill to it. Every road here bends around a river nobody can see.');

-- routes, and the authoritative stop order
insert into routes (combo_key, draft, note) values ('fire-fleet-marks', true, null);
insert into routes (combo_key, draft, note) values ('fire-fleet-rivers', true, 'Vertical slice. Three stops of an eventual eighteen, chosen to cover the three stop types rather than three of a kind: a plain stop, a soft-prompt stop, and a location-gated stop.');
insert into route_stops (combo_key, position, stop_id) values ('fire-fleet-rivers', 1, 'st-brides-spire');
insert into route_stops (combo_key, position, stop_id) values ('fire-fleet-rivers', 2, 'st-dunstan-west-clock');
insert into route_stops (combo_key, position, stop_id) values ('fire-fleet-rivers', 3, 'holborn-viaduct-fleet');
insert into routes (combo_key, draft, note) values ('fire-fleet-roman', true, null);
insert into routes (combo_key, draft, note) values ('fire-marks-rivers', true, null);
insert into routes (combo_key, draft, note) values ('fire-marks-roman', true, null);
insert into routes (combo_key, draft, note) values ('fire-rivers-roman', true, null);
insert into routes (combo_key, draft, note) values ('fleet-marks-rivers', true, null);
insert into routes (combo_key, draft, note) values ('fleet-marks-roman', true, null);
insert into routes (combo_key, draft, note) values ('fleet-rivers-roman', true, null);
insert into routes (combo_key, draft, note) values ('marks-rivers-roman', true, null);

commit;
